# Generated by Django 4.0.4 on 2022-05-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fee',
            field=models.IntegerField(blank=True),
        ),
    ]
