# Generated by Django 4.0.4 on 2022-05-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsApp', '0002_alter_student_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fee',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
