# Generated by Django 4.0.4 on 2022-05-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsApp', '0003_alter_student_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rate',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
