# Generated by Django 4.0.4 on 2022-05-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsApp', '0004_student_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
